<script>
	import CardList from "./cards.svelte";
	import Card from "./lib/components/card.svelte";

	let basics;
	let holos;
	let galaxies;
	let radiant;
	let basicGallery;
	let vee;
	let veeUltra;
	let veeAlt;
	let veeMax;
	let veeMaxAlt;
	let veeStar;
	let trainerHolo;
	let rainbow;
	let gold;
	let veeGallery;

	const getCards = async () => {
		let promiseArray = [];

		let cardFetch = await fetch("/data.json");
		let cards = await cardFetch.json();
		// window.cards = cards;

		basics = cards.slice(0, 3);
		holos = cards.slice(6, 12);
		galaxies = cards.slice(12, 15);
		radiant = cards.slice(15, 18);
		basicGallery = cards.slice(60, 63);
		vee = cards.slice(18, 21);
		veeUltra = cards.slice(21, 24);
		veeAlt = [...cards.slice(27, 30), ...cards.slice(33, 36)];
		veeMax = cards.slice(24, 27);
		veeMaxAlt = [cards[36], cards[31], cards[37]];
		veeStar = cards.slice(39, 42);
		trainerHolo = cards.slice(42, 48);
		rainbow = cards.slice(48, 51);
		gold = cards.slice(51, 54);
		veeGallery = cards.slice(63, 69);

		return cards;
	};
</script>

<main>
	<header>
		<h1>Real Fake Synergy NFTs</h1>

		<section class="intro">
			<p>
				Mint <mark>memorable NFTs</mark> from Synergy synths!
				<br />
				You will be able to <mark>redeem your synths</mark> by smelting the NFT.
			</p>
			<br>
			<p>
				Mining natural resources hurts the environment. That's why we decided to create Synergy — a synthetic assets protocol with cutting-edge DeFi maths.
			</p>
			<br>
			<p>
				A large part of mining is powered by <mark>the need for speculation</mark>. By making speculators trade synths instead of the real thing, we can offset real-world resource mining.
			</p>
			<br>
			<p>
				Another big part of mining natural resources is creating jewelry. But now you can <mark>create jewelry with synthetic gold!</mark>
			</p>
		</section>

		<div class="showcase">
			{#await getCards()}
				loading...
			{:then cards}
				<Card
					name={cards[51].name}
					img={cards[51].images.large}
					number={cards[51].number}
					supertype={cards[51].supertype}
					subtypes={cards[51].subtypes}
					rarity={cards[51].rarity}
					showcase={true}
				/>
			{/await}
		</div>

		<section class="info">
			<h2><em>(Click a card to take a closer look at it!)</em></h2>

			<hr />

			<p class="small">
				Artwork generated by Stable Diffusion and 
				<a href="https://github.com/simeydotme/pokemon-cards-css"><svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>GitHub</title><path d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"/></svg>pokemon-cards-css</a>

			</p>
		</section>
	</header>

	<h1>Precious Collectibles</h1>
	<p>
		We will create <mark>seasonal collections</mark> and <mark>community drops</mark> that will have special rarity effects.
		<br />
		Some of them you can only mint within a specific timeframe.
	</p>
	<br>
	<p>
		Right now you can mint:
	</p>
	<ul>
		<li>A 1oz Gold Coin — The best non-fungible fungible currency.</li>
		<li>A 5oz Gold Nugget — A rocky boy.</li>
		<li>A 10oz Gold Ingot — I can't believe it's not butter.</li>
		<li>A Cube of pure gold — For 1000oz or more, you can show that you're the biggest nature lover. <s>You can touch it</s> It looks nice.</li>
	</ul>
	<CardList>
		{#await getCards()}
			loading...
		{:then cards}
			{#each vee as card, id}
				<Card
					name={card.name}
					img={card.images.large}
					number={card.number}
					supertype={card.supertype}
					subtypes={card.subtypes}
					rarity={card.rarity}
				/>
			{/each}
		{/await}
	</CardList>

	<p>
		After minting you can check out your NFTs on 
		<a href="https://testnets.opensea.io/collection/synergy-nfts">Opensea</a>

	</p>

</main>

<style>
	main {
		color: white;
		padding: 50px;
		max-width: 1200px;
		margin: auto;
	}

	header {
		margin-bottom: 4rem;
		display: grid;
		grid-template-columns: 1fr;
		grid-gap: 30px;
		max-width: 900px;
		margin: auto;
	}

	header h2 {
		margin-top: 0;
		font-weight: 100;
	}

	header svg {
		width: 1em;
		fill: currentColor;
		position: relative;
		top: 2px;
		margin: 0 5px;
		display: inline-block;
	}

@media screen and (min-width: 600px) {
	header {
		grid-template-columns: 50% 1fr;
	}
	.showcase {
		grid-column: 2;
		grid-row: 1/5;
	}
	.intro, .info, .author {
		grid-column: 1;
	}
}

	@media screen and (min-width: 900px) {
		header {
			grid-template-columns: 60% 1fr;
		}
	}

	.showcase {
		z-index: 99;
		max-width: min(330px, 80vw);
		margin: auto;
	}

	h1 {
		margin-top: 0;
		margin-bottom: 0.25em;
	}

	p {
		margin: 0 0 0.25em;
		line-height: 1.5;
	}

	p.small {
		font-size: 0.875rem;
		opacity: 0.75;
	}

	h1,
	h2,
	h3 {
		font-family: 'Roboto Condensed';
	}

	h2 {
		margin-top: 4em;
		margin-bottom: 0.25em;
	}

	h2 + p,
	h2 + p + p {
		font-style: italic;
		margin-bottom: 1em;
	}

	hr {
		border: none;
		background: white;
		height: 1px;
		opacity: 0.25;
		margin: 1em -1em;
	}

	h1 sup {
		font-weight: 300;
		font-size: 0.5em;
	}

	h2 sup {
		font-weight: 300;
		font-size: 0.75em;
	}

	mark {
		background: #ffb403;
		color: black;
		font-style: italic;
		font-weight: bold;
		padding-inline: 0.25em;
		border-radius: 3px;
	}
</style>
